### ISSUE TITLE
Confused on where .txt files come from?

### ISSUE THREAD

**Issue by sidul001** [gd-goblin/C-3PO_Motion_Retargeting_Module#22]
Hello,

I am really confused on how the dataset itself is organized. I have downloaded the skeleton data. I have downloaded some of video data from couple subject from the original the dataset. 

When running training, I getting the following error: 

Traceback (most recent call last):
  File "training.py", line 216, in <module>
    np_train_skel_data, shape, fc_list = load_skeleton_data(skeleton_train_dict[i])
  File "C:\Users\zulmo\Documents\MotionREtargeting\C-3PO_Motion_Retargeting_Module\CommonObject.py", line 122, in load_skeleton_data
    with open(full_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/skeleton/A022TrainSkeletonFrame(37613_76).txt'

Where do I get txt files from? And can you please in detail explain how the data is organized and named? (cause it seems that the structure is different from what the original skeleton data is).

THANK YOU IN ADVANCE! Very impressive work! Please help me out!

**Comment by gd-goblin** [comment]
Hello,
Sorry for the late response.

The text files like 'A022TrainSkeletonFrame(37613_76).txt' should firstly
be generated from the original data by the "save_skeleton_data()".
Please refer to the "skeleton_encoding.py" file.

The script does a few pre-processing steps such as excluding noisy skeleton
data (those are marked in the text files of "exception_file_list" folder),
and skeleton coordinate transformation.

We did not change the original NTU-DB dataset structure, but just filtered
noisy ones out except for the coordinate transform of the skeleton.


Best regards






2021년 9월 9일 (목) 오전 12:03, sidul001 ***@***.***>님이 작성:
